services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: simple-rag-postgres
    environment:
      POSTGRES_DB: simplerag
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d simplerag"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
