--liquibase formatted sql

--changeset luanvv:007-create-chat-memory-table
CREATE TABLE chat_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    message_type VARCHAR(20) NOT NULL CHECK (message_type IN ('USER', 'ASSISTANT', 'SYSTEM')),
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata TEXT
);

CREATE INDEX idx_chat_memory_conversation_id ON chat_memory(conversation_id);
CREATE INDEX idx_chat_memory_created_at ON chat_memory(created_at);

--rollback DROP TABLE chat_memory;
